// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $icon from "./routes/icon.tsx";
import * as $index from "./routes/index.tsx";
import * as $deno_blocks_ide_island from "./islands/deno_blocks_ide_island.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/icon.tsx": $icon,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/deno_blocks_ide_island.tsx": $deno_blocks_ide_island,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
